### PR TITLE
Lawrence 78 implement fade out effect as user scrolls

### PR DESCRIPTION
**Pull request by lawrenceslng**
I implemented the fade out effect only with the 1st page and with hardcoded scroll trigger rather than with opacity change. For V2 of this feature we should investigate opacity change but I haven't gotten it to work yet

### CODE REVIEW

**Comment by shenghungKuan** [comment]
https://whoisryosuke.com/blog/2020/handling-scroll-based-animations-in-react/#using-a-library
I found this one is using opacity change as scrolling. Hope it will be helpful for you.

This is the codesandbox demo:
https://codesandbox.io/s/react-scroll-animation-forked-lrhtt?file=/src/index.js

**Comment by lawrenceslng** [comment]
I made some changes so that it is actually changing opacity instead of a fade trigger now

https://github.com/GayaHealth/Gaya_Website/assets/38678774/aaebc1c6-db25-4fc0-8f5b-4d6527808ec6

**Comment by lawrenceslng** [comment]
@shenghungKuan and @zhunan123 can you guys check this PR and approve if it looks good?

**Review by zhunan123 — APPROVED** [review]
Looks good! feel free to merge it

**Pull request merged**
