### PR TITLE
initial commit to implement transition in landing page

### PR DESCRIPTION
**Pull request by zhunan123**
So far i have the transition looks like this, working on to make inner circle not rotating but grow as we scroll down.

### CODE REVIEW

**Comment by zhunan123** [comment]
Updated the current transition effect.
https://github.com/GayaHealth/Gaya_Website/assets/47227727/cf2ba097-3495-4158-82f1-012f9efe781b

**Review by lawrenceslng — CHANGES_REQUESTED** [review]
2 small changes:

1) Can you make the arrows rotate slower when scrolling? Seems to be moving a little fast
2) Can you have a gap between the arrows? Having them separated rather than touching looks better (like in the Figma)

**Comment by zhunan123** [comment]
> 2 small changes:
> 
> 1. Can you make the arrows rotate slower when scrolling? Seems to be moving a little fast
> 2. Can you have a gap between the arrows? Having them separated rather than touching looks better (like in the Figma)

@lawrenceslng I have made some changes to adjust it, can you check it again here? https://gaya-website-1-dsz9q0diy-gayahealth.vercel.app/

**Review by lawrenceslng — APPROVED** [review]
Looks Good!

**Pull request merged**
