### PR TITLE
initial commit for test cases

### PR DESCRIPTION
**Pull request by zhunan123**
I initialized the tests folder and added a sample test for `Header.test.js`. in `/client`, just ran `npm test `should see the test result. Probably need to add more component functional test if this method works fine.

test-demo

### CODE REVIEW

**Comment by lawrenceslng** [comment]
this basically just tests if the components are in the DOM right?

**Comment by zhunan123** [comment]
> this basically just tests if the components are in the DOM right?

yeah, but we can add functions to test the states as well, I added one to check once the nav button clicked, the fontSize should be changed and the page should be scrolled to top.

**Comment by lawrenceslng** [comment]
Nice, how do you want to split up the work on writing tests?

**Comment by zhunan123** [comment]
> Nice, how do you want to split up the work on writing tests?

Do we need to have test cases for every single component? I am thinking maybe to start writing the test from components we wrote by our own.

**Comment by zhunan123** [comment]
Added more test cases.

test-demo-1

**Review by shenghungKuan — APPROVED** [review]

**Pull request merged**
